### ISSUE TITLE
add option to filter by champion name

### ISSUE THREAD

**Issue by radlinskii** [radlinskii/lol-mastery-chest-viewer#13]
We should add filtering by champion name option to our app. to filter by name Create another input which on change will be filtering the results displayed on the screen.

**Comment by km4** [comment]
@radlinskii Add some select with all names of champions?
When I select Jinx then all others champions on the table should be invisible (hide)?

**Comment by radlinskii** [comment]
I would make it another text input. Select would have the same problem that the simple list has - it would be very long and making it hard to find the champion you want to check.

**Comment by km4** [comment]
Roger that. I will try to create some input for search/filter champions

**Comment by km4** [comment]
@radlinskii feel free to CR :)

**Comment by km4** [comment]
https://github.com/radlinskii/lol-mastery-chest-viewer/pull/41 @radlinskii we can close this issue :)
