### ISSUE TITLE
add option to show only champions with chest granted/available

### ISSUE THREAD

**Issue by miszkur** [radlinskii/lol-mastery-chest-viewer#31]
Add a checkbox to filter out champions with chest already granted.

**Comment by dimitrov-d** [comment]
Hi, I can solve this

**Comment by radlinskii** [comment]
Sure, go ahead.

**Comment by radlinskii** [comment]
I've updated https://github.com/radlinskii/lol-mastery-chest-viewer#installation in case you had trouble with getting started

**Comment by km4** [comment]
@dimitrov-d you working on this or I can take issue?

**Comment by dimitrov-d** [comment]
@km4 You can go ahead and work on it

**Comment by km4** [comment]
alright, I try today push PR for that.
